### PR TITLE
Rails 7 Upgrade

### LINKED ISSUE #975: Upgrade to Rails 7
A new version of Rails is out! We'd like to upgrade to it this year now that things are looking pretty stable.

There is a guide to this process that we should be able to follow: https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-6-1-to-rails-7-0

### PR DESCRIPTION
**Pull request by archonic**
# What it does

Upgrades to Rail 7 and closes #975.

# Why it is important

Upgrades are good :+1:

# Implementation notes

There was one deprecated use of `to_s` which we can now use `to_sf` for. A few other deprecations had no real impact according to tests. There was some host redirection issues as well which were fixed in one case by just allowing an external redirect to a payment completion page. Another fix for a host redirect was actually just a `www` issue. The fix assumes that the shortlinks controller is not meant to be used for external URLs.

# Your bandwidth for additional changes to this PR

* I have the time and interest to make additional changes to this PR based on feedback.

### CODE REVIEW

**Review by jim — CHANGES_REQUESTED** [review]
Awesome! Thanks for working on this for us. I was worried about this upgrade but it looks to have not been too bad after all.

I read through the changes and everything generally looks good. The Github checks detected a few things to address before we merge this:
* There are [a couple test failures](https://github.com/chicago-tool-library/circulate/actions/runs/6366149790/job/17335300027?pr=1138). They seem to be related to timezones or date comparisons.
* Standard found some code formatting issues.
* ERBLint flagged a place where a safe operator should be used.

The commands to fix 2 and 3 are [in the README](https://github.com/chicago-tool-library/circulate#code-formatting-and-linting)- for the most part it's usually a one-liner to resolve them.

Let me know if you I can help at all with resolving these minor issues. This is really close and it'll be so exciting to have this upgrade done.

**Comment by phinze** [comment]
This is looking really close and would be great to get merged. LMK if you could use any help on the last mile @archonic I'd be happy to pitch in!

**Comment by archonic** [comment]
I'm away til the 22nd, but happy to take another swing after that. Or if someone else wants to fix the failures, please do.

**Comment by phinze** [comment]
Hope your time away was good @archonic 😄

How are you feeling about coming back around to this? If you don't think you'll have the time in the next week or so, I'll probably take it over the finish line. There are a few things in Rails 7 that I'd like to use in some other work.

Let me know either way!

**Comment by archonic** [comment]
@phinze Hi, it was great! I thought I'd have more time for this but I won't be able to do anything on it till next weekend. Feel free to take it across the finish line!

**Comment by phinze** [comment]
No problem @archonic I'll take it from here - thanks for all the work on it so far!

**Comment by phinze** [comment]
Will finish this up and bring it home in #1178 🚀

**Pull request closed without merging**
