### PR TITLE
Improve hold text on the item page

### LINKED ISSUE #1205: Improve hold interaction on item page
On the item page, we show a box with some text in it above the button that allows someone to put an item on hold:

Image

The text is fairly complicated, though, and if someone is logged in, we should be able to tell them if they'll be first in line or not.

So, let's add a conditional in the view template when folks are logged in and display this if there aren't any other holds on the item:

> Placing a hold means you would like to be on the waiting list to use this item. No one else is waiting on this item, so once you place it on hold, you'll have a week to come to the library and pick it up.

If there are holds on the item, let's display this:

> Placing a hold means you would like to be on the waiting list to use this item. There are currently $NUMBER people waiting to use this item, and you will be $NUMBER + 1. When it is your turn to borrow the item, we'll send you an email and you'll have one week to come pick it up.

When someone has the item on hold, change the heading of the box to say "You have this item on hold". If the person is the next in line, the text should say:

> You have until $HOLD_EXPIRES_AT to pick up this item.

Otherwise, the text should say:

> You are on the waitlist for this item. There are X people ahead of you on the list.

Also, replace the "Place Hold" button with one that says "Cancel hold". When clicked, it should cancel the hold. Make this button not the primary button color.

Additionally:
* Make the "schedule an appointment" link the primary button color
* When the user is redirected to the item page after placing a hold, see if we can have the "you have this item on hold" be scrolled into view.

### PR DESCRIPTION
**Pull request by djcunningham0**
# What it does

Fixes #1205. Improves the text on the item page related to placing the item on hold.

* The heading now says "You have this item on hold" if the user has placed a hold (it used to always say "You can place this item on hold").
* Text is more informative and conditional on whether the user has placed a hold, the number of users ahead of the logged-in user on the wait list, and whether the item is ready for pickup.
* The "Place a hold" button only appears if it is needed.
* Added a conditional "Remove Hold" button when the user has already placed a hold.

# Why it is important

The old text was long and difficult to understand. See #1205 for more details.

# UI Change Screenshot

The screenshots below show the new UI in a variety of scenarios.

### Logged-in user does not have a hold

Item available, no holds:

image

Item available, someone else has a hold:

image

Item checked out:

image

### Logged-in user has a hold

Item available, first in line:

image

Item available, first in line, appointment scheduled:

image

Item available, not first in line:

image

Item checked out:

image

### User is not logged in

image

# Implementation notes

I tried to reuse existing functionality where possible (for example, I used the `render_remove_link` function for the "Remove Hold" button).

### CODE REVIEW

**Comment by djcunningham0** [comment]
I'm open to feedback on the text and the design of the page. Feel free to nitpick if you'd like to see something changed.

**Comment by djcunningham0** [comment]
Also, the "Remove Hold" button redirects the user to the Holds page after clicking it. I thought it might be more intuitive to stay on the current item page, but I couldn't figure out how to make the button work without redirecting. Any ideas on how to do that? (Or if people prefer that it redirects to the Holds page, that's fine too.)

**Comment by djcunningham0** [comment]
Looks like it's failing a couple of the tests in `test/system/holds_test.rb`. Those tests need to be updated to reflect the new expected behavior. I'll try to make those updates later this week.

**Review by jim — COMMENTED** [review]
These changes look good! We might try to tighten up the whitespace a bit, but I don't think that's a blocking issue.

If you need any help with the system tests, it might be something to work on together on a Monday night.

**Comment by djcunningham0** [comment]
I pushed a couple more commits to:
1. Handle the case when the logged-in user has the item checked out. (This will resolve #1423 as a side effect)
2. Make many of the messages more concise.

The screenshots below show the updated screens for all cases where I made changes:

### Logged-in user has the item checked out

No appointment scheduled:
image

No appointment scheduled, overdue:
image

Appointment scheduled:
image

Renewal requested:
image

Renewal denied:
image


### Logged-in user does not have a hold

Item available, no holds:
image

Item available, someone else has a hold:
image

Item checked out:
image


### Logged-in user has a hold

Item available, first in line:
image

Item available, first in line, appointment scheduled:
image

Item available, not first in line:
image

Item checked out:
image

**Review by jim — APPROVED** [review]
This is awesome! I really appreciate how thorough you were with covering all of the different cases.

**Pull request merged**
